import type { Metadata } from 'next'

import { Box, CssBaseline } from '@mui/material'

import authenticated from '@/hooks/auth/authenticated'

import Providers from '@/providers/auth'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const isAuthenticated = await authenticated()

  return (
    <html lang="en">
      <body>
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          <Box>{children}</Box>
        </Providers>
      </body>
    </html>
  )
}
